// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  lookahead = 19,
  atxHeadingStart = 20,
  AtxHeadingContent = 1,
  thematicBreakStart = 21,
  lineStart = 22,
  lineStartIndented = 23,
  lineStartDedented = 24,
  blankLine = 25,
  eof = 26,
  anything = 27,
  AtxHeading = 3,
  AtxHeadingMarker = 4,
  ThematicBreak = 5,
  IndentedCodeBlock = 6,
  _Line = 7,
  Line = 8,
  Paragraph = 9
