// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  nonIndentSpaces = 15,
  blockIndent = 16,
  blankLine = 17,
  thematicBreakInner = 18,
  ThematicBreak = 2,
  IndentedCodeBlock = 3,
  Line = 4,
  GenericBlock = 5
