// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  nonIndentSpaces = 23,
  blockIndent = 24,
  blankLine = 25,
  eof = 26,
  thematicBreakInner = 27,
  anything = 28,
  AtxHeading = 2,
  _a = 8,
  AtxHeadingText = 9,
  ThematicBreak = 10,
  IndentedCodeBlock = 11,
  Line = 12,
  GenericBlock = 13
