// This file was generated by lezer-generator. You probably shouldn't edit it.
import {Parser} from "lezer"
import {lookahead, scanAtxHeading, scanAtxHeadingContent, scanThematicBreak, scanLineStart, scanEof, eatAnything} from "./tokens"
import {NodeProp} from "lezer"
export const parser = Parser.deserialize({
  states: "&YOPO!VOOOdO!VO'#CjOOOP'#C`'#C`OwO%XO'#C_O!UOpO'#CaO!YO#tO'#CdO!^O#tO'#CbO!bO!VO'#ClOOOP(3@z(3@zOOOP'#Ce'#CeO!uO!VO'#CmOOOP(3@{(3@{OOOP'#Cx'#CxOOOP(3@x(3@xQOOOOOOOOP,59Q,59QOOOP'#Cz'#CzOOOP,58y,58yO#YO!cO,58yO#aOWO,58yO#eO#tO,58{O#YO!cO,59OOOOP'#Cc'#CcO#YO!cO,58|OOOP,59S,59SOOOP,59T,59TOOOP1G.e1G.eO#iO%XO1G.eO#YO!cO1G.gOOOP1G.j1G.jO#sOpO1G.hOOOP7+$P7+$PO#YO!cO7+$POOOP7+$R7+$RO#}OpO'#CkOOOO(3@y(3@yO$XOpO7+$SOOOP<<Gk<<GkOOOO,59R,59ROOOP<<Gn<<Gn",
  stateData: "$]~dQOeSOfTOgUOiZOb^P~dQOeSOfTOgUOiZOb^X~j`OkbOmcOo`O~fdO~keO~kfO~fTOb`Xd`Xe`Xg`Xi`X~iZObaXdaXeaXfaXgaX~j`Oo`O~PkO~klO~j`OkpOo`O~fTOisOh_P~fTOisOh_X~hwO~",
  goto: "#eoPPPptppx{p!U![!b!i!p!s!vpPPPPPPPPPP!zP#OT[OPTROPRgUUWOPVTsnrQPOR_PQrnRvrSVOPRhVSYOPRiYR^ORtnTXOPT]OPQaRQjbQmeQngQokQqlRup",
  nodeNames: "⚠ AtxHeadingContent Document AtxHeading AtxHeadingMarker ThematicBreak IndentedCodeBlock Line Line Paragraph",
  nodeProps: [
    [NodeProp.top, 2,true]
  ],
  repeatNodeCount: 4,
  tokenData: "w~RSXY_YZj]^opq_~dQm~XY_pq_~oOo~~tPo~YZj",
  tokenizers: [0, lookahead, scanAtxHeading, scanAtxHeadingContent, scanThematicBreak, scanLineStart, scanEof, eatAnything],
  topRules: {"Document":[0,2]},
  specializeTable: 0,
  tokenPrec: 0
})
